404.md

- Updated link on the 404 page to go to correct help center link

Update 404 links

---

administrators/index.md
administrators/interactions.md
administrators/opportunity-metrics.md
release-notes/index.md
release-notes/sep-04-2020.md

Removed Sept. 4 release notes.

Added Oct. 16 release notes

---

administrators/opportunity-metrics.md

Trying to fix the broken link on the administrator/opportunity-metrics page.

Fix broken link

---

_includes/components/nav/sidenav.html
applicants/find.md
getting-started/web-browser.md
profile/badges.md
release-notes/index.md
release-notes/sep-18-2020.md

edited series section to say occupational series

---

_includes/components/nav/sidenav.html
administrators/opportunity-metrics.md
opportunity-creators/complete-opportunity.md

Will also update the sidenav to include a link to this new page.

Add new complete opportunity page

---

_includes/components/nav/sidenav.html
administrators/add-community-manager.md
administrators/add-member.md
administrators/approve-opportunity.md

Creating a couple new pages in help center

Add new how to for how to approve an opportunity

---

_includes/components/nav/sidenav.html
administrators/add-participant.md
administrators/delete-opportunity.md

Can go at any time. Will have a handful of new help pages.

New page for adding a participant to opportunity

---

_includes/components/nav/sidenav.html
administrators/change-community-owner.md
administrators/change-opportunity-owner.md
administrators/delete-participant.md
release-notes/index.md

Added release notes for Dec. 11

---

_includes/components/nav/sidenav.html
opportunity-creators/add-skills.md
opportunity-creators/index.md
opportunity-creators/top-10-tips.md
profile/index.md
release-notes/index.md
release-notes/oct-02-2020.md

Made several edits to help content to support the skills engine release for Jan. 22.
- Added new page within the Opportunity Creator section called How to add skills to an opportunity.
- Edited How to create a profile to talk about adding skills
- Edited How to create an opportunity to change the page name to How to create and post an opportunity, as well as update the page to include skills engine info.
- Edited How to write a great opportunity (10 tips) to add info about skills
- Edited Sidenav file to add new page and edit the page name.

Dalenard21 patch skills engine jan 22

---

opportunity-creators/cancel-opportunity.md

Need to update the permalink, section and category to fix broken url

fixing permalink, section and category

---

release-notes/index.md
release-notes/oct-30-2020.md

Moved Oct. 30 release notes to an archive page.

Added release notes for March 19 2021

---

_includes/components/nav/sidenav.html
administrators/add-community-manager.md
administrators/add-member.md
administrators/add-participant.md
administrators/approve-opportunity.md
administrators/change-opportunity-owner.md
administrators/delete-opportunity.md
administrators/delete-participant.md
administrators/opportunity-metrics.md
release-notes/dec-11-2020.md
release-notes/index.md

Updated several pages for the April 19 release.
Updated the following:
What do the opportunity metrics mean?
How to approve an opportunity
How to add a member to a community
How to make a member a community manager
How to add a participant to a community
How to change the owner of an opportunity
How to delete an opportunity
How to delete a participant from an opportunity
Release notes
Sidenav to add "How to add a member to a community" in the Administrator sidenav

Dalenard21 patch april 19 release

---

release-notes/index.md
release-notes/jan-22-2021.md

Also moved Jan 22 release notes to archive page

added April 30 release notes

---

release-notes/feb-05-2021.md
release-notes/index.md

Also removed Feb 5 2021 release notes.

Added release notes for May 14 2021

---

_includes/components/nav/sidenav.html
administrators/index.md
administrators/metrics.md

Update the first page users see when they go to the Administrator section.

Update Administrator section index

---

release-notes/index.md
release-notes/mar-19-2021.md

Added release notes for May 28, 12.3 release

---

release-notes/apr-19-2021.md
release-notes/apr-30-2021.md
release-notes/index.md

Also archived april 19 and 30 release notes
will also include new pages for april 19 and april 30

added 12.5 release notes for june 25

---

applicants/find.md
applicants/participate.md
index.html
profile/index.md

Changed Federal Government to federal government across a few pages per issue 594

Lowercased Federal Government

---

opportunity-creators/select-applicant.md
profile/index.md
release-notes/index.md
release-notes/may-14-2021.md

added july 9 release notes and archive page for May 14

Added july 9 release notes

---

release-notes/index.md
release-notes/may-28-2021.md

Also moved May 28 to an archive page

added release notes for July 23 2021

---

_includes/components/nav/sidenav.html
opportunity-creators/complete-opportunity.md
opportunity-creators/extend-opportunity.md

Update sidebar navigation fixes for the Opportunity Creators section.

Help Center nav fix updates

---

profile/badges.md
release-notes/index.md
release-notes/jun-11-2021.md

Moved June 11 notes to archive page
Will also include a new page for June 11 and updates to badges content

added release notes for Aug. 8

---

release-notes/index.md
release-notes/jun-25-2021.md

Moved June 25 release notes to archive page

Added release notes for Aug 20 2021

---

_includes/components/nav/sidenav.html
communities/add-discussion.md
communities/join-discussion.md

Add new discussion board content to Communities section

Add discussion board pages

---

release-notes/index.md
release-notes/jul-09-2021.md

Moved July 9 release notes to archive page

Added release notes for Sep. 3

---

release-notes/aug-06-2021.md
release-notes/index.md

Oct. 1 release notes and archive page

Added Oct. 1 release notes

---

release-notes/index.md

Updated release notes for October 29 release.

Added release notes for 13.4

---

release-notes/index.md
release-notes/sep-03-2021.md

Moved sept. 3 release notes to archvie

Added Nov. 12 release notes

---

release-notes/index.md
release-notes/sep-17-2021.md

added Nov. 29, 13.6 release notes

---

release-notes/index.md
release-notes/oct-15-2021.md

13.8 and 13. 9 releases. Also moved Oct. 15 release notes to own page

added release notes for Jan. 7 2022 release

---

release-notes/index.md
release-notes/oct-29-2021.md

moved oct. 29 release notes to separate page.

added 14.0 release notes

---

_includes/components/nav/sidenav.html
communities/community-manager-playbook.md
release-notes/index.md
release-notes/nov-12-2021.md

Goes out with 14.2, Feb. 18 release

Add new page for community manager playbook

---

release-notes/index.md
release-notes/nov-26-2021.md

Removed Nov. 26 release notes to archive page.

added March 4 release notes.

---

_includes/components/nav/sidenav.html
profile/privacy-settings.md
release-notes/dec-10-2021.md
release-notes/index.md

Moved Dec. 10 2021 release notes to archive page

Added release notes for 14.4 release

---

release-notes/index.md
release-notes/jan-07-2022.md

Goes out April 15, 2022
Will also include an archive page for Jan 7 2022

Release notes for 14.6 release

---

release-notes/index.md

Release notes for release 14.7

added release notes for April 29

---

_includes/components/nav/secondary.html
_includes/components/nav/sidenav.html
administrators/approve-opportunity.md
administrators/change-opportunity-owner.md
administrators/delete-opportunity.md
administrators/opportunity-metrics.md
applicants/find.md
applicants/participate.md
applicants/save-search.md
opportunity-creators/cancel-opportunity.md
opportunity-creators/complete-opportunity.md
opportunity-creators/index.md
opportunity-creators/opportunity-status.md
opportunity-creators/post-to-community.md
opportunity-creators/select-applicant.md
profile/badges.md

Pushing Internship content updates

Internship content updates 1.0

---

videos/tutorials.md

Adding a new video to the Videos page. How to apply for a VSFS internship.  Can you please review to make sure it looks okay and then push to production?

added video for how to apply for VSFS internships

---

release-notes/index.md
release-notes/jul-2022.md

Dalenard21 patch 1 release 15.7 20220916

---

communities/index.md

Added link for PDF to community index for direct download

Cyber community download link

---

release-notes/index.md

Added Nov. 14 release notes

---

videos/tutorials.md

Finally finished this video and requesting to add to the help section. Thanks!

How to complete an internship

---

release-notes/index.md
release-notes/sep-2022.md

16.2 release notes and archive page for Sept. 2022

Dalenard21 patch 1 release 16 2 20221128

---

release-notes/index.md
release-notes/oct-2022.md

Dalenard21 patch 1 release 16.6 20230120

---

release-notes/index.md
release-notes/nov-2022.md

Release notes for 16.7, Feb. 3 2023 release - updates to what's new and archive page for nov. 2022

Dalenard21 patch 1 release 16.7 20230202

---

release-notes/index.md

To go into production on 2/17/23

Added 16.8 release notes for Feb. 17 2023 release

---

release-notes/dec-2022.md
release-notes/index.md

Changes to support 16.9 release - updating the release notes. Goes out on March 3, 2023

Dalenard21 patch 1 release 16.9 20230303

---

release-notes/index.md

Added 17.1 release notes

---

release-notes/index.md
release-notes/jan-2023.md

Dalenard21 patch 1 release 17.2 20230414

---

release-notes/feb-2023.md
release-notes/index.md

moving feb. 2023 to archive page.

Added 17.4 release notes

---

release-notes/index.md

Goes out with release 17.6 on June 9, 2023

Added release ntoes for 17.6

---

release-notes/apr-2023.md
release-notes/index.md

Moved april 2023 release notes to new page.

Added 17.8 release notes

---

release-notes/index.md

Added release notes for 17.9 release

Added 17.9 release notes

---

release-notes/index.md

Updated the what's new page with 18.0 release notes. Goes to production on Aug. 4 2023

Added 18.0 release notes

---

release-notes/index.md

Release notes for 18.1 for open opps

Added 18.1 release notes

---

release-notes/index.md
release-notes/may-2023.md

Moved May 2023 release notes to archive page

Added 18.2 release notes and moved May 2023

---

release-notes/index.md
release-notes/jun-2023.md

Also removed June release notes and moved to archive page

Added 18.4 release notes

---

release-notes/index.md

18.5 release notes for Oct. 13 release.

Added release notes for 18.5

---

index.html

Added a flyer for employees and supervisors to the getting started page.

Added flyers to getting started page

---

opportunity-creators/add-skills.md

Reverts USAJOBS/openopps-help#179

Revert "Delete opportunity-creators/add-skills.md"

---

opportunity-creators/commitment.md
release-notes/aug-2023.md
release-notes/index.md

moved august 2023 release notes to it's own page.

Added 18.8 release notes

---

release-notes/index.md
release-notes/sep-2023.md

Also moving Sep. 2023 release notes to archive page

Added release notes for 19.0 release

---

administrators/opportunity-metrics.md
opportunity-creators/index.md
opportunity-creators/opportunity-status.md
opportunity-creators/select-applicant.md

Removed recurring, added reviewing applicants, updated what's included in total published and total created, fixed a broken link

VSFS content updates

---

getting-started/who-can-participate.md
opportunity-creators/accept-applications.md
opportunity-creators/cancel-opportunity.md
opportunity-creators/post-to-community.md
release-notes/index.md
release-notes/jan-2024.md

Bolded federal employee

---

videos/tutorials.md

Adding add applicant video

---

_includes/components/nav/sidenav.html
opportunity-creators/available-students.md

Two changes.  Added a new page under Creators for available students and updated the sidenav file to include that link.

Pull request for new available student page and updated sidenav

---

release-notes/index.md

Release notes for 20.2

---

release-notes/index.md

Add release notes for sprint 20.3

Add release notes for sprint 20.3

---

release-notes/index.md

Added 20.4 Release Notes
